### PR TITLE
Fix build errors in IccCmm header on Linux

### PR DESCRIPTION
**Pull request by ahmedmchamed**
Added missing forward declaration for the `CIccXformNDLut` class to accommodate friend declaration within `CIccApplyNDLutXform` - friend declaration alone does not constitute a general declaration

Build error was: 
`IccCmm.h:1246:37 error: expected ')' before '*' token`

### CODE REVIEW

**Review by xsscx — CHANGES_REQUESTED** [review]
Hello @ahmedmchamed,

Thank you for your PR. The build status of the PR has errors as shown below.

## [PR85](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/85) Build Reproduction 

### [PR85](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/85) Build Host 

```
uname -a
Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

GCC Version:
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

Clang Version:
Ubuntu clang version 14.0.0-1ubuntu1.1
Target: x86_64-pc-linux-gnu

ASAN Version (from GCC):
Version: 4:11.2.0-1ubuntu1

ASAN Version (libasan package):
Version: 11.4.0-1ubuntu1~22.04

libxml2 Version:
2.9.13

libtiff Version:
4.3.0-6ubuntu0.9
```

### [PR85](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/85) Build Instructions
**Build Result: Not Passing**
```
cd /tmp
wget https://github.com/InternationalColorConsortium/DemoIccMAX/archive/5f1d19e14dfa56adcbb52d09f7fb039870ee53a9.zip
unzip 5f1d19e14dfa56adcbb52d09f7fb039870ee53a9.zip
cd DemoIccMAX-5f1d19e14dfa56adcbb52d09f7fb039870ee53a9/Build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev  Cmake
make -j$(nproc) 2>&1 | grep 'error:'
```


### [PR85](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/85) Build Errors
 ```
/tmp/DemoIccMAX-5f1d19e14dfa56adcbb52d09f7fb039870ee53a9/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:79:10: fatal error: ..\IccCommon\IccCmmConfig.h: No such file or directory
/tmp/DemoIccMAX-5f1d19e14dfa56adcbb52d09f7fb039870ee53a9/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:81:10: fatal error: ..\IccCommon\IccCmmConfig.h: No such file or directory
 ```
## [PR85](https://github.com/InternationalColorConsortium/DemoIccMAX/pull/85) Summary

[Issue 77](https://github.com/InternationalColorConsortium/DemoIccMAX/issues/77) tracks these and other compile errors being resolved by the Author.

Please update this PR if you have working build instructions or if I can provide any additional details.

Thank you for submitting a PR.

**Comment by ahmedmchamed** [comment]
Hi @xsscx, many thanks for the comment
That's a change pushed up to the branch to add an additional `CMakeLists.txt` under a new directory, `IccCommon`, that is a sub-directory under `Build -> Cmake -> Tools` to allow cmake to capture the additional `IccCmmConfig` source files
The includes for `IccCmmConfig` in `iccApplyProfiles.cpp` and `iccApplyNamedCmm.cpp` have also been modified to remove the full path, as those files can now be included as normal given that cmake can now see them

Noticing there's an additional dependency on [nlohmann's json library](https://github.com/nlohmann/json) that can also fail the build unless a user has explicitly set that library up locally, and without the project presumably modifying the `CMAKE_MODULE_PATH` variable. 

Not quite sure how to do that yet though to be honest. Would this change be in scope for this pr in any case?

Thanks

**Comment by xsscx** [comment]
Hi @ahmedmchamed,

Thank you for the updated PR and details. I updated the Github Action for your latest Commit ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280.

### ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280 Reproduction
**Result: Not Passing**
```
cd /tmp
wget https://github.com/InternationalColorConsortium/DemoIccMAX/archive/ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280.zip
unzip ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280.zip
cd DemoIccMAX-ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280/Build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev  Cmake
make -j$(nproc) 2>&1 | grep 'error:'
...
/tmp/DemoIccMAX-ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280/Build/Cmake/Tools/IccCommon/../../../../Tools/CmdLine/IccCommon/IccJsonUtil.h:4:10: fatal error: 'nlohmann/json.hpp' file not found
/tmp/DemoIccMAX-ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280/Build/Cmake/Tools/IccCommon/../../../../Tools/CmdLine/IccCommon/IccJsonUtil.h:4:10: fatal error: 'nlohmann/json.hpp' file not found
/tmp/DemoIccMAX-ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280/Tools/CmdLine/IccApplyProfiles/iccApplyProfiles.cpp:79:10: fatal error: 'IccCmmConfig.h' file not found
/tmp/DemoIccMAX-ff2fb95bb8bb2fa7d013ee40b55edeb5a703d280/Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp:81:10: fatal error: 'IccCmmConfig.h' file not found
```

If you have build instructions for a successful compilation please update the PR. My thought is that once the Author of Commit f891074a0f1c9d61a3dfa53749265f8c14ed4ee6 completes refactoring then a PR would be appropriate, building on that updated reference implementation. As to the use of the json dependency, that appears to also be based on Commit f891074a0f1c9d61a3dfa53749265f8c14ed4ee6.

My suggestion is:
```
git bisect bad b90ac3933da99179df26351c39d8d9d706ac1cc6*
```

Once f891074a is refactored and compiles I can PR a build script. If you have insight for what would be helpful, please do update this PR.

---
For anyone wanting to Cherry Pick their way to the most recent build:

### Cherry Picking Example

```
cd /tmp
git clone https://github.com/InternationalColorConsortium/DemoIccMAX.git
cd DemoIccMAX
git checkout f891074a0f1c9d61a3dfa53749265f8c14ed4ee6
git fetch origin
git cherry-pick 35787aa9ad33dc27448f1af68a0a5bfdde4fffba
git cherry-pick 1ed936f2d398c12c04b570f7cd3ad251c39bb483
git cherry-pick e71eacfa550ac9a092903ecc24feba9ae32ebaae
git cherry-pick 4f354f4d034a88230e6cabbc1f84ff0d9a4556ae
git cherry-pick c0ab97ddd1a0f792c8afb7a061135bc7c87f5854
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev Build/Cmake
make -j$(nproc) 2>&1 | grep 'error:'
```
**Result: Pass**

Keep adding **git cherry-pick** for the Commits you want.

----

For those seeking a more elegant Build Solution, consider the following.
## Runner Example

```
name: C/C++ CI with Packaging

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository at the base commit
      uses: actions/checkout@v4
      with:
        ref: f891074a0f1c9d61a3dfa53749265f8c14ed4ee6

    - name: Set up Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    - name: Fetch the latest changes
      run: git fetch origin

    - name: Cherry-pick commit 9c66ef2
      run: |
        git cherry-pick 9c66ef27a8f834c538430d17abaf14af32ee34e2 || (
          echo "Conflict occurred during cherry-pick of commit 9c66ef2" && git cherry-pick --abort
        )
    - name: Cherry-pick commit 35787aa
      run: |
        git cherry-pick 35787aa9ad33dc27448f1af68a0a5bfdde4fffba || (
          echo "Conflict occurred during cherry-pick of commit 35787aa" && git cherry-pick --abort
        )
    - name: Cherry-pick commit ede72ec
      run: |
        git cherry-pick ede72eca10cd8a19af90adc716e264c53c2f474d || (
          echo "Conflict occurred during cherry-pick of commit ede72ec" && git cherry-pick --abort
        )
    - name: Cherry-pick commit 1ed936f
      run: |
        git cherry-pick 1ed936f2d398c12c04b570f7cd3ad251c39bb483 || (
          echo "Conflict occurred during cherry-pick of commit 1ed936f" && git cherry-pick --abort
        )
    - name: Cherry-pick commit 163b38b
      run: |
        git cherry-pick 163b38b20779149967e5cf78f2300fbef790dc2b || (
          echo "Conflict occurred during cherry-pick of commit 163b38b" && git cherry-pick --abort
        )
    - name: Cherry-pick commit e71eacf
      run: |
        git cherry-pick e71eacfa550ac9a092903ecc24feba9ae32ebaae || (
          echo "Conflict occurred during cherry-pick of commit e71eacf" && git cherry-pick --abort
        )
    - name: Cherry-pick commit 4f354f4
      run: |
        git cherry-pick 4f354f4d034a88230e6cabbc1f84ff0d9a4556ae || (
          echo "Conflict occurred during cherry-pick of commit 4f354f4" && git cherry-pick --abort
        )
    - name: Cherry-pick commit 1ed936f
      run: |
        git cherry-pick 1ed936f2d398c12c04b570f7cd3ad251c39bb483 || (
          echo "Conflict occurred during cherry-pick of commit 1ed936f" && git cherry-pick --abort
        )
    - name: Cherry-pick commit 163b38b
      run: |
        git cherry-pick 163b38b20779149967e5cf78f2300fbef790dc2b || (
          echo "Conflict occurred during cherry-pick of commit 163b38b" && git cherry-pick --abort
        )
    - name: Cherry-pick commit e71eacf
      run: |
        git cherry-pick e71eacfa550ac9a092903ecc24feba9ae32ebaae || (
          echo "Conflict occurred during cherry-pick of commit e71eacf" && git cherry-pick --abort
        )
    - name: Cherry-pick commit c0ab97d
      run: |
        git cherry-pick c0ab97ddd1a0f792c8afb7a061135bc7c87f5854 || (
          echo "Conflict occurred during cherry-pick of commit c0ab97d" && git cherry-pick --abort
        )
  
    - name: Cherry-pick commit c0ab97d
      run: |
        git cherry-pick c0ab97ddd1a0f792c8afb7a061135bc7c87f5854 || (
          echo "Conflict occurred during cherry-pick of commit c0ab97d" && git cherry-pick --abort
        )
  
    - name: Cherry-pick commit 55f4f77
      run: |
        git cherry-pick -m 1 55f4f773498a294d35fe5d26a6fd5909dda8d57f || (
          echo "Conflict occurred during cherry-pick of commit 55f4f77" && git cherry-pick --abort
        )
    - name: Cherry-pick commit dc78afc
      run: |
        git cherry-pick -m 1 dc78afcfe9e8cf0dd027e8dd30e21bebf101ffaa || (
          echo "Conflict occurred during cherry-pick of commit dc78afc" && git cherry-pick --abort
        )
  
    - name: Run CMake and Build
      run: |
        cmake -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-g -fsanitize=address,undefined -fno-omit-frame-pointer -Wall" -Wno-dev Build/Cmake
        make -j10
    - name: Install the Build
      run: make install

    - name: Set executable permissions for binaries
      run: |
        find $HOME/.local/bin -type f -exec chmod +x {} \;
    - name: Package build outputs
      run: |
        mkdir -p build_artifacts/bin
        mkdir -p build_artifacts/lib
        cp -r $HOME/.local/bin/* build_artifacts/bin/
        cp -r $HOME/.local/lib/* build_artifacts/lib/
        cp -r $HOME/.local/include build_artifacts/include
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build_artifacts/
```

For those looking to bypass the Compile Issues, I posted Ubuntu x86_64, macos x86_64 and arm64 packages at URL https://github.com/xsscx/PatchIccMAX/tags

Thank you again for updating the PR. I'll keep an eye out for your updates.

Let me know if I can provide any additional information or help to compile etc.

**Comment by xsscx** [comment]
Closing this PR. 

Workaround information provided. If additional help can be provided, please re-open this ISsue or open a new Issue. 

Thank you again for your PR.
